### ISSUE TITLE
Cloudformation failed to complete

### ISSUE THREAD

**Issue by paulwakeford** [jros2300/reservedinstances#1]
Hi, this looks like an excellent tool, however the Cloudformation template is not completing for me. It looks like the source code is missing from your S3 bucket? Is there a new location?

        {
            "StackId": "arn:aws:cloudformation:ap-southeast-2:<my account>:stack/reservedinstances/e2a4df80-8cea-11e5-8b9f-5081ed124436",
            "EventId": "RIApplicationVersion-CREATE_FAILED-2015-11-17T05:20:24.566Z",
            "ResourceStatus": "CREATE_FAILED",
            "ResourceType": "AWS::ElasticBeanstalk::ApplicationVersion",
            "Timestamp": "2015-11-17T05:20:24.566Z",
            "ResourceStatusReason": "Unable to download from S3 location (Bucket: amzsup  Key: reservedinstances-master.zip). Reason: Moved Permanently",
            "StackName": "reservedinstances",
            "ResourceProperties": "{\"ApplicationName\":\"reservedinstances-RIApplication-E6M5GOKKOZ9B\",\"Description\":\"Version 1.0\",\"SourceBundle\":{\"S3Bucket\":\"amzsup\",\"S3Key\":\"reservedinstances-master.zip\"}}\n",
            "PhysicalResourceId": "",
            "LogicalResourceId": "RIApplicationVersion"
        },

**Comment by paulwakeford** [comment]
Downoloaded and hosted the code in my own bucket to work around this issue.

**Comment by jros2300** [comment]
I've updated the S3 bucket, but copy the ZIP file to your own bucket is the best option, so you can maintain your version.
