### ISSUE TITLE
Cloudformation failed to complete - second error

### ISSUE THREAD

**Issue by paulwakeford** [jros2300/reservedinstances#2]
16:39:04 UTC+1100	CREATE_FAILED	AWS::ElasticBeanstalk::Environment	RIEnvironment	No Solution Stack named '64bit Amazon Linux 2015.03 v1.4.1 running Ruby 2.2 (Passenger Standalone)' found

**Comment by paulwakeford** [comment]
That stack is no longer supported/available - https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts.platforms.html#concepts.platforms.ruby

Trying:

"SolutionStackName": "64bit Amazon Linux 2015.09 v2.0.4 running Ruby 2.2 (Passenger Standalone)",

**Comment by paulwakeford** [comment]
OK so stack completion completed but the worker EB env is marked as bad. Errors:


[2015-11-17T06:02:36.900Z] ERROR [22216] : Command CMD-Startup(stage 1) failed!
[2015-11-17T06:02:36.901Z] INFO  [22216] : Command processor returning results: 
{"status":"FAILURE","api_version":"1.0","results":[{"status":"FAILURE","msg":"missing required parameter params[:table_name] - (ArgumentError). \nHook /opt/elasticbeanstalk/addons/sqsd/hooks/firstboot/02-start-sqsd.sh failed. For more detail, check /var/log/eb-activity.log using console or EB CLI","returncode":1,"events":[{"msg":"Successfully loaded 2 scheduled tasks from cron.yaml.","severity":"INFO","timestamp":1447740156}]}]}

-------------------------------------
/var/log/aws-sqsd/default.log
-------------------------------------
2015-11-17T06:02:35Z init: initializing aws-sqsd 2.0 (2015-02-18)
2015-11-17T06:02:36Z schedule-parser: Successfully loaded 2 scheduled tasks from file /var/app/current/cron.yaml .
2015-11-17T06:02:36Z init: missing required parameter params[:table_name] (ArgumentError)
	at /opt/elasticbeanstalk/lib/ruby/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.1.23/lib/aws-sdk-core/param_validator.rb:26:in `validate!'
	from /opt/elasticbeanstalk/lib/ruby/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.1.23/lib/aws-sdk-core/param_validator.rb:11:in `validate!'
	from /opt/elasticbeanstalk/lib/ruby/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.1.23/lib/aws-sdk-core/plugins/param_validator.rb:20:in `call'
	from /opt/elasticbeanstalk/lib/ruby/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.1.23/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
	from /opt/elasticbeanstalk/lib/ruby/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.1.23/lib/aws-sdk-core/plugins/dynamodb_simple_attributes.rb:112:in `call'
	from /opt/elasticbeanstalk/lib/ruby/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.1.23/lib/aws-sdk-core/plugins/param_converter.rb:21:in `call'
	from /opt/elasticbeanstalk/lib/ruby/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.1.23/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /opt/elasticbeanstalk/lib/ruby/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.1.23/lib/seahorse/client/request.rb:70:in `send_request'
	from /opt/elasticbeanstalk/lib/ruby/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.1.23/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from /opt/elasticbeanstalk/lib/ruby/lib/ruby/gems/2.2.0/gems/aws-sqsd-2.0/vendor/AWSMACLE/lib/leader_election/storage_manager.rb:81:in `update_registration'
	from /opt/elasticbeanstalk/lib/ruby/lib/ruby/gems/2.2.0/gems/aws-sqsd-2.0/vendor/AWSMACLE/lib/leader_election/storage_manager.rb:19:in `verify_table'
	from /opt/elasticbeanstalk/lib/ruby/lib/ruby/gems/2.2.0/gems/aws-sqsd-2.0/vendor/AWSMACLE/lib/leader_election/daemon.rb:37:in `initialize'
	from /opt/elasticbeanstalk/lib/ruby/lib/ruby/gems/2.2.0/gems/aws-sqsd-2.0/vendor/AWSMACLE/lib/leader_election.rb:8:in `new'
	from /opt/elasticbeanstalk/lib/ruby/lib/ruby/gems/2.2.0/gems/aws-sqsd-2.0/vendor/AWSMACLE/lib/leader_election.rb:8:in `create'
	from /opt/elasticbeanstalk/lib/ruby/lib/ruby/gems/2.2.0/gems/aws-sqsd-2.0/lib/aws-sqsd/cron.rb:241:in `leader_election_daemon'
	from /opt/elasticbeanstalk/lib/ruby/lib/ruby/gems/2.2.0/gems/aws-sqsd-2.0/lib/aws-sqsd/cron.rb:30:in `initialize'
	from /opt/elasticbeanstalk/lib/ruby/lib/ruby/gems/2.2.0/gems/aws-sqsd-2.0/lib/aws-sqsd/daemon.rb:44:in `new'
	from /opt/elasticbeanstalk/lib/ruby/lib/ruby/gems/2.2.0/gems/aws-sqsd-2.0/lib/aws-sqsd/daemon.rb:44:in `initialize'
	from /opt/elasticbeanstalk/lib/ruby/lib/ruby/gems/2.2.0/gems/aws-sqsd-2.0/bin/aws-sqsd:34:in `new'
	from /opt/elasticbeanstalk/lib/ruby/lib/ruby/gems/2.2.0/gems/aws-sqsd-2.0/bin/aws-sqsd:34:in `start'
	from /opt/elasticbeanstalk/lib/ruby/lib/ruby/gems/2.2.0/gems/aws-sqsd-2.0/bin/aws-sqsd:83:in `launch'
	from /opt/elasticbeanstalk/lib/ruby/lib/ruby/gems/2.2.0/gems/aws-sqsd-2.0/bin/aws-sqsd:111:in `<top (required)>'
	from /opt/elasticbeanstalk/lib/ruby/bin/aws-sqsd:23:in `load'
	from /opt/elasticbeanstalk/lib/ruby/bin/aws-sqsd:23:in `<main>'

**Comment by paulwakeford** [comment]
Ok I think this is because the supplied cron.yaml has white space at the end of most lines which causes it to barf. I removed them, rezipped and uploaded as a new app version and it looks from the log to be working now. I'll delete my env and start again from scratch and raise some PRs if it all works.

**Comment by paulwakeford** [comment]
Unsure about the cron fix now. It was working but has now stopped again. I'll test some more.

**Comment by arnib** [comment]
Hi @paulwakeford Did you figure out what was causing your issues?
It seems like this is still relevant, as the SolutionStackName also caused me issues.

Seems like the current version is now `64bit Amazon Linux 2016.03 v2.1.2 running Ruby 2.2 (Passenger Standalone)`, but even with changing that I'm having difficulties getting the stack started.

**Comment by jros2300** [comment]
Hi, I've updated the cloudformation stack, and now it works again
