### ISSUE TITLE
Error applying recommendations

### ISSUE THREAD

**Issue by paulwakeford** [jros2300/reservedinstances#4]
D, [2015-11-17T13:23:44.994962 #22374] DEBUG -- :   [1m[36m (0.8ms)[0m  [1mBEGIN[0m
D, [2015-11-17T13:23:44.996588 #22374] DEBUG -- :   [1m[35mSQL (0.7ms)[0m  INSERT INTO `recommendations` (`accountid`, `rid`, `instancetype`, `count`, `timestamp`, `created_at`, `updated_at`) VALUES ('myaccount', 'myrid', 'r3.2xlarge', 1, '2015-11-17 13:23:44', '2015-11-17 13:23:44', '2015-11-17 13:23:44')
D, [2015-11-17T13:23:45.004087 #22374] DEBUG -- :   [1m[36m (7.2ms)[0m  [1mCOMMIT[0m
D, [2015-11-17T13:23:45.867054 #22374] DEBUG -- :   [1m[35m (0.8ms)[0m  BEGIN
D, [2015-11-17T13:23:45.868622 #22374] DEBUG -- :   [1m[36mSQL (0.9ms)[0m  [1mINSERT INTO `recommendations` (`accountid`, `rid`, `az`, `count`, `timestamp`, `created_at`, `updated_at`) VALUES ('myid', 'myrid2', 'ap-southeast-2a', 2, '2015-11-17 13:23:45', '2015-11-17 13:23:45', '2015-11-17 13:23:45')[0m
D, [2015-11-17T13:23:45.877083 #22374] DEBUG -- :   [1m[35m (8.2ms)[0m  COMMIT
I, [2015-11-17T13:23:46.588773 #22374]  INFO -- : Completed 500 Internal Server Error in 5237ms (ActiveRecord: 20.4ms)
F, [2015-11-17T13:23:46.589591 #22374] FATAL -- : 
Aws::EC2::Errors::InvalidInput (Invalid value for 'targetReservedInstancesConfigurations'. Total normalized instance units in Reserved Instances and target configurations do not match.):
  lib/aws_common.rb:222:in `apply_recommendation'
  app/controllers/summary_controller.rb:44:in `block in apply_recommendations'
  app/controllers/summary_controller.rb:42:in `each'
  app/controllers/summary_controller.rb:42:in `apply_recommendations'

**Comment by jros2300** [comment]
You're right, I'm going to modify lib/aws_common.rb to fill in the request with the rest of instances in the RI.

**Comment by jros2300** [comment]
I've uploaded a new version with the problem solved
